In [4]:
import numpy as np

In [9]:
a = np.array([[1,2,3], [4,5,6]])

In [10]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [24]:
b = [[2], [4]]
add = a*b
sum = a+b
print(add,sum, sep='\n')

[[ 2  4  6]
 [16 20 24]]
[[ 3  4  5]
 [ 8  9 10]]
