In [3]:
import numpy as np

In [4]:
a = np.array([[1,2,3], [4,5,6]])

In [5]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
b = [[2], [4]]
add = a*b
sum = a+b
print(add,sum, sep='\n')

[[ 2  4  6]
 [16 20 24]]
[[ 3  4  5]
 [ 8  9 10]]


In [7]:
defa = add * sum
defa

array([[  6,  16,  30],
       [128, 180, 240]])

In [8]:
defa

array([[  6,  16,  30],
       [128, 180, 240]])

In [9]:
a = np.array([[1,2], [3,4]])
b = [1,3]
c = [[1], [3]]

In [10]:
sum = a*b
sum

array([[ 1,  6],
       [ 3, 12]])

In [11]:
sum = a*c
sum

array([[ 1,  2],
       [ 9, 12]])

In [12]:
matrix = [[1,2,3],[4,5,6],[7,8,9]]

In [13]:
matrix = np.transpose(matrix)
matrix

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [1]:
import time

In [4]:
def one():
    start = time.time()
    a = 1+1
    end = time.time()
    diff = end - start
    return a, start,end,
print(one(


(2, 1766507469.3557167, 1766507469.3557167)
