In [1]:
import numpy as np
from torch.distributed.fsdp.wrap import size_based_auto_wrap_policy

### Basic Array Operations

#### Operations with 1-d array

In [15]:
arr = np.array([10, 20, 30, 40, 50])
arr, arr.ndim, arr.shape, len(arr)

(array([10, 20, 30, 40, 50]), 1, (5,), 5)

#### Operations with 2-d array

In [17]:
arr_2 = np.array([[10, 20, 30, 40, 50], [1,2,3,4,5]])
arr_2

array([[10, 20, 30, 40, 50],
       [ 1,  2,  3,  4,  5]])

In [23]:
arr_2.ndim, len(arr_2), arr_2.size, arr_2.dtype, type(arr_2),

(2, 2, 10, dtype('int64'), numpy.ndarray)

In [10]:
#
matr = np.zeros(shape=2, dtype=int)
matr_b = np.zeros(shape=(2,2))
matr, matr_b

(array([0, 0]),
 array([[0., 0.],
        [0., 0.]]))

#### How to fill np.array

In [26]:
arr_1 = np.zeros(shape=(3))
arr_2 = np.zeros(shape=(3,5))
arr_1, arr_2

(array([0., 0., 0.]),
 array([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]))

In [ ]:
arr = np.full()