In [8]:
import numpy as np

### Basic Array Operations

#### Operations with 1-d array

In [9]:
arr = np.array([10, 20, 30, 40, 50])
arr, arr.ndim, arr.shape, len(arr)

(array([10, 20, 30, 40, 50]), 1, (5,), 5)

#### Operations with 2-d array

In [10]:
arr_2 = np.array([[10, 20, 30, 40, 50], [1,2,3,4,5], [0,0,0,0,0]])
arr_2

array([[10, 20, 30, 40, 50],
       [ 1,  2,  3,  4,  5],
       [ 0,  0,  0,  0,  0]])

In [11]:
arr_2.ndim, len(arr_2), arr_2.size, arr_2.dtype, type(arr_2),

(2, 3, 15, dtype('int64'), numpy.ndarray)

In [12]:
#
matr = np.zeros(shape=2, dtype=int)
matr_b = np.zeros(shape=(2,2))
matr, matr_b

(array([0, 0]),
 array([[0., 0.],
        [0., 0.]]))

#### How to fill np.array

In [13]:
arr_1 = np.zeros(shape=(3))
arr_2 = np.zeros(shape=(3,5))
arr_1, arr_2

(array([0., 0., 0.]),
 array([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]))

In [23]:
arr[::]

array([10, 20, 30, 40, 50])

In [47]:
arr1 = np.array([[1,2,3], [4,5,6]])
arr2 = np.array([[1,2]])

In [48]:
arr1, arr2

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[1, 2]]))

In [49]:
sum = arr1 * arr2
sum

ValueError: operands could not be broadcast together with shapes (2,3) (1,2) 