In [10]:
import numpy as np
# from jedi.inference.utils import to_list
# from numpy.conftest import dtype

In [11]:
a = np.array([[1,2,3], [4,5,6]])

In [12]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
b = [[2], [4]]
add = a*b
sum = a+b
print(add,sum, sep='\n')

[[ 2  4  6]
 [16 20 24]]
[[ 3  4  5]
 [ 8  9 10]]


In [14]:
defa = add * sum
defa

array([[  6,  16,  30],
       [128, 180, 240]])

In [15]:
defa

array([[  6,  16,  30],
       [128, 180, 240]])

In [16]:
a = np.array([[1,2], [3,4]])
b = [1,3]
c = [[1], [3]]

In [17]:
sum = a*b
sum

array([[ 1,  6],
       [ 3, 12]])

In [18]:
sum = a*c
sum

array([[ 1,  2],
       [ 9, 12]])

In [19]:
matrix = [[1,2,3],[4,5,6]]#,[7,8,9]\
matrix

[[1, 2, 3], [4, 5, 6]]

In [20]:
matrix
matrix = np.transpose(matrix)
matrix, len(matrix)

(array([[1, 4],
        [2, 5],
        [3, 6]]),
 3)

In [21]:
# Есть матрица, нужно ее транспонировать

In [22]:
arr_2 = matrix
arr_2.ndim, len(arr_2), arr_2.size, arr_2.dtype, type(arr_2),

(2, 3, 6, dtype('int64'), numpy.ndarray)

In [23]:
matrix2 = np.empty((matrix.ndim, len(matrix)), dtype=int)
for i in range(len(matrix)):
    for j in range(len(matrix[i])):
        matrix2[j][i] = matrix[i][j]
print(matrix2)

[[1 2 3]
 [4 5 6]]


In [24]:
matrix2, matrix2.tolist(), len(matrix)

(array([[1, 2, 3],
        [4, 5, 6]]),
 [[1, 2, 3], [4, 5, 6]],
 3)

In [25]:
ar = list([1,2,3])
type(ar)

list

In [26]:
np.array(ar)

array([1, 2, 3])

In [27]:
matrix

array([[1, 4],
       [2, 5],
       [3, 6]])

In [30]:
rows = len(matrix)
cols = len(matrix[0])

In [40]:
emp = np.empty((rows, cols), dtype=int)
emp[0][0]/10

np.True_