In [1]:
import numpy as np
# from jedi.inference.utils import to_list
# from numpy.conftest import dtype

In [2]:
a = np.array([[1,2,3], [4,5,6]])

In [3]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
b = [[2], [4]]
add = a*b
sum = a+b
print(add,sum, sep='\n')

[[ 2  4  6]
 [16 20 24]]
[[ 3  4  5]
 [ 8  9 10]]


In [5]:
defa = add * sum
defa

array([[  6,  16,  30],
       [128, 180, 240]])

In [6]:
defa

array([[  6,  16,  30],
       [128, 180, 240]])

In [7]:
a = np.array([[1,2], [3,4]])
b = [1,3]
c = [[1], [3]]

In [8]:
sum = a*b
sum

array([[ 1,  6],
       [ 3, 12]])

In [9]:
sum = a*c
sum

array([[ 1,  2],
       [ 9, 12]])

In [10]:
matrix = [[1,2,3],[4,5,6]]#,[7,8,9]\
matrix

[[1, 2, 3], [4, 5, 6]]

In [11]:
matrix
matrix = np.transpose(matrix)
matrix, len(matrix)
rows = len(matrix)
cols = len(matrix[0])

In [12]:
# Есть матрица, нужно ее транспонировать

In [13]:
arr_2 = matrix
arr_2.ndim, len(arr_2), arr_2.size, arr_2.dtype, type(arr_2),

(2, 3, 6, dtype('int64'), numpy.ndarray)

In [14]:
matrix2 = np.empty((matrix.ndim, len(matrix)), dtype=int)
for i in range(rows):
    for j in range(cols):
        matrix2[j][i] = matrix[i][j]
print(matrix2)

[[1 2 3]
 [4 5 6]]


In [15]:
matrix2, matrix2.tolist(), len(matrix)

(array([[1, 2, 3],
        [4, 5, 6]]),
 [[1, 2, 3], [4, 5, 6]],
 3)

In [16]:
ar = list([1,2,3])
type(ar)

list

In [17]:
np.array(ar)

array([1, 2, 3])

In [18]:
matrix

array([[1, 4],
       [2, 5],
       [3, 6]])

In [19]:
emp = np.empty((rows, cols), dtype=int)
emp[0][0]/10

np.float64(48103633726.2)

In [20]:
a = np.array([[1,2], [3,4]])
b = [1,3]
c = [[1], [3]]


In [21]:
print(a*b)

[[ 1  6]
 [ 3 12]]


In [22]:
print(a*c)

[[ 1  2]
 [ 9 12]]
