In [2]:
import numpy as np

In [3]:
a = np.array([[1,2,3], [4,5,6]])

In [4]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
b = [[2], [4]]
add = a*b
sum = a+b
print(add,sum, sep='\n')

[[ 2  4  6]
 [16 20 24]]
[[ 3  4  5]
 [ 8  9 10]]


In [6]:
defa = add * sum
defa

array([[  6,  16,  30],
       [128, 180, 240]])

In [7]:
defa

array([[  6,  16,  30],
       [128, 180, 240]])

In [8]:
a = np.array([[1,2], [3,4]])
b = [1,3]
c = [[1], [3]]

In [9]:
sum = a*b
sum

array([[ 1,  6],
       [ 3, 12]])

In [10]:
sum = a*c
sum

array([[ 1,  2],
       [ 9, 12]])

In [11]:
matrix = [[1,2,3],[4,5,6],[7,8,9]]

In [12]:
matrix = np.transpose(matrix)
matrix

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [13]:
# Есть матрица, нужно ее транспонировать

In [30]:
arr_2 = matrix
arr_2.ndim, len(arr_2), arr_2.size, arr_2.dtype, type(arr_2),

(2, 3, 9, dtype('int64'), numpy.ndarray)

In [33]:
matrix2 = np.empty((len(matrix), len(matrix)), dtype=int)
for i in range(len(matrix)):
    for j in range(len(matrix[i])):
        matrix2[j][i] = matrix[i][j]
print(matrix2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
