In [2]:
import numpy as np
# from jedi.inference.utils import to_list
# from numpy.conftest import dtype

In [3]:
a = np.array([[1,2,3], [4,5,6]])

In [4]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
b = [[2], [4]]
add = a*b
sum = a+b
print(add,sum, sep='\n')

[[ 2  4  6]
 [16 20 24]]
[[ 3  4  5]
 [ 8  9 10]]


In [6]:
defa = add * sum
defa

array([[  6,  16,  30],
       [128, 180, 240]])

In [7]:
defa

array([[  6,  16,  30],
       [128, 180, 240]])

In [8]:
a = np.array([[1,2], [3,4]])
b = [1,3]
c = [[1], [3]]

In [9]:
sum = a*b
sum

array([[ 1,  6],
       [ 3, 12]])

In [10]:
sum = a*c
sum

array([[ 1,  2],
       [ 9, 12]])

In [11]:
matrix = [[1,2,3],[4,5,6]]#,[7,8,9]\
matrix

[[1, 2, 3], [4, 5, 6]]

In [12]:
matrix
matrix = np.transpose(matrix)
matrix, len(matrix)
rows = len(matrix)
cols = len(matrix[0])

In [13]:
# Есть матрица, нужно ее транспонировать

In [14]:
arr_2 = matrix
arr_2.ndim, len(arr_2), arr_2.size, arr_2.dtype, type(arr_2),

(2, 3, 6, dtype('int64'), numpy.ndarray)

In [15]:
matrix2 = np.empty((matrix.ndim, len(matrix)), dtype=int)
for i in range(rows):
    for j in range(cols):
        matrix2[j][i] = matrix[i][j]
print(matrix2)

[[1 2 3]
 [4 5 6]]


In [16]:
matrix2, matrix2.tolist(), len(matrix)

(array([[1, 2, 3],
        [4, 5, 6]]),
 [[1, 2, 3], [4, 5, 6]],
 3)

In [17]:
ar = list([1,2,3])
type(ar)

list

In [18]:
np.array(ar)

array([1, 2, 3])

In [19]:
matrix

array([[1, 4],
       [2, 5],
       [3, 6]])

In [20]:
emp = np.empty((rows, cols), dtype=int)
emp[0][0]/10

np.float64(2589596844444886.0)